version: "3.7"

volumes:
  crm-support:
    name: crm-support
    external: false

services:
  mongo:
    image: mongo:latest
    restart: always

    volumes:
      - crm-support:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - target: 8081
        published: 8089
        protocol: tcp
        mode: host

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

