apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
spec:
  containers:
    - image: mongo-express
      name: mongo-express
      ports:
        - containerPort: 8081
          hostPort: 8081
          protocol: TCP
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
